name: charmed-etcd-snap # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: etcd is a distributed reliable key-value store for distributed systems. # 79 char long summary
description: |
  etcd is a distributed reliable key-value store for the most critical data of a distributed system.
  etcd is written in Go and uses the Raft consensus algorithm to manage a highly-available replicated log.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  etcd:
    daemon: simple
    command: bin/etcd
    plugs:
      - network-bind
  etcdctl:
    command: bin/etcdctl
    plugs:
      - network-bind
      - home
  etcdutl:
    command: bin/etcdutl
    plugs:
      - network-bind
      - home

parts:
  etcd:
    plugin: make
    build-snaps: [go/latest/stable]
    source: https://git.launchpad.net/etcd
    source-type: git
    source-branch: main
    override-build: |
      make build
      cp -r bin $CRAFT_PART_INSTALL/