# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  build:
    name: Build snap
    uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@v29.0.5

  test:
    name: Test snap
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo snap install yq

      - name: Download snap package(s)
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ needs.build.outputs.artifact-prefix }}-*
          merge-multiple: true

      - name: Install snap package(s) and start the etcd service
        run: |
          sudo snap install --dangerous charmed-etcd*.snap
          sudo snap start charmed-etcd.etcd

      - name: Check etcd service status and run etcdctl, etcdutl and tools
        run: |
          sudo systemctl status snap.charmed-etcd.etcd.service | grep 'active (running)'

          # Wait for etcd to start and listen on port 2379
          sleep 5

          expected_version="$(cat snap/snapcraft.yaml | yq .version)"
          version="$(curl -L http://localhost:2379/version | yq -p=json .etcdserver)"
          if [ "$expected_version" != "$version" ]; then
            echo "Error: etcd Version is ${version}, expected ${expected_version}"
            exit 1
          fi

          charmed-etcd.etcdctl version
          charmed-etcd.etcdutl version
          
          echo "\nTesting benchmark...\n"
          charmed-etcd.benchmark txn-mixed --endpoints http://localhost:2379 --total 20 | grep -E 'Total Read Ops|Total Write Ops|Requests/sec'
          
          echo "\nTesting etcd-dump-logs...\n"
          sudo charmed-etcd.etcd-dump-logs /var/snap/charmed-etcd/common/var/lib/etcd/ | grep -E 'WAL metadata|WAL entries'
          
          echo "\nTesting etcd-dump-metrics...\n"
          charmed-etcd.etcd-dump-metrics --addr http://localhost:2379/metrics | grep -E 'etcd_server_version|etcd_cluster_version'
          
          echo "\nTesting rw-benchmark...\n"
          
          cd ~/snap/charmed-etcd/common/
          
          RATIO_LIST="1/1" \
          VALUE_SIZE_POWER_RANGE="8 8" \
          CONN_CLI_COUNT_POWER_RANGE="1 1" \
          REPEAT_COUNT=1 \
          RUN_COUNT=100 \
          charmed-etcd.rw-benchmark
          
          echo "\nChecking for files\n"
          ls -lah ~/snap/charmed-etcd/common
          
          echo "\nTesting rw-heatmaps...\n"
      
          CSV_FILE=$(ls -t ~/snap/charmed-etcd/common/result-*.csv | head -n1)
          echo "Using CSV file: $CSV_FILE"
          
          charmed-etcd.rw-heatmaps "$CSV_FILE" -o ~/snap/charmed-etcd/common/heatmap-test -t test-run
          test -f ~/snap/charmed-etcd/common/heatmap-test_read.jpg
          test -f ~/snap/charmed-etcd/common/heatmap-test_write.jpg

      - name: Run tests
        run: |
          charmed-etcd.etcdctl endpoint health | grep 'is healthy'
          charmed-etcd.etcdctl put greeting "Hello, etcd" | grep 'OK'
          charmed-etcd.etcdctl get greeting | grep 'Hello, etcd'

      - name: Run Performance checks
        run: |
          charmed-etcd.etcdctl check perf | grep 'PASS'
