#!/bin/sh -e

# This hook is called when the snap is installed
# copy the configuration file to the snap's data directory
cp "${SNAP}"/config/etcd.conf.yml "${SNAP_DATA}"/etcd.conf.yml
chown -R 584788:584788 "${SNAP_DATA}"/*

# create the data directory
DATA="${SNAP_COMMON}"/var/lib/etcd
mkdir -p "${DATA}"
chmod -R 770 "${SNAP_COMMON}"
chmod 750 "${DATA}"
chown -R 584788:584788 "${SNAP_COMMON}"/*
