#!/bin/sh -e

# This hook is called when the snap is installed
# copy the configuration file to the snap's data directory
cp "${SNAP}"/config/etcd.conf.yml "${SNAP_DATA}"/etcd.conf.yml
chown -R 584788:584788 "${SNAP_DATA}"/*

# create the data directory only if not exists
DATA="${SNAP_COMMON}"/var/lib/etcd
if [ ! -d "${DATA}" ]; then
  mkdir -p "${DATA}"
fi

# If we just created the directory, we set up permissions
if [ stat -c '%u' "${DATA}" == 0 ]; then
    chmod -R 770 "${SNAP_COMMON}"
    chmod 750 "${DATA}"
fi

chown -R 584788:584788 "${SNAP_COMMON}"/*
